version: '3'
services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    volumes:
      - ./:/scripts
    command: /bin/bash -c "cd /scripts/scripts && chmod +x scripts.sh && ./scripts.sh && apt-get update && apt install -y cron"
    #command: /bin/bash -c "cd /scripts/scripts && ls && chmod +x verifScript.sh && ./verifScript.sh"
    privileged: true



  ubuntu2:
    image: ubuntu:latest
    container_name: ubuntu2
    command: /bin/bash -c " mkdir -p backup && ls /backup -l && apt-get update "
    depends_on:
      - ubuntu
 

    
    

